version: '3'

services:
  db:
    build: ./mysql
    container_name: 'share_db'
    environment:
      MYSQL_DATABASE: share_development
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - '5306:3306'
  nuxt:
    image: palladion/pl-nuxt:1.0.1
    container_name: 'share_nuxt'
    command: yarn dev
    volumes:
      - ./nuxt:/usr/my_projects
      - ./nuxt/node_modules:/usr/my_projects/node_modules
    ports:
      - '5600:3000'
  laravel:
    image: palladion/pl-laravel
    container_name: 'share_laravel'
    command: php artisan serve --host 0.0.0.0 --port=3000
    ports:
      - '4000:3000'
    volumes:
      - ./laravel:/usr/my_projects
volumes:
  db-store:
    driver: local